general:
    efield_v_cm: 500
    temperature_k: 87.0
    drift_time_max_us: 66.0
light: 
    event_selection_mode: veto_only
    waveform_analysis: each_channel
    general_analysis_channels: [5,6,7]
    pileup_analysis_channels: [4]
    light_gamma_thr_mV: 0.0
    light_cosmic_thr_mV: 700.0
    pre_roi_window_us: 0.1
    post_roi_window_us: 5.0
    out_roi_peak_thr_mV: 100.0
    pedestal_correction: true
    pedestal_range_min: -100.0
    pedestal_range_max: -50.0
    digitizer_offset_correction: true
    digitizer_offset_range_start_index: 0
    digitizer_offset_range_stop_index: 100
    fft_filter: false
    fft_low_frequency: 0.0
    fft_high_frequency: 0.1
    transimpedance_feedback_resistance_ohm: 50.0
    output_impedance_ohm: 50.0
    light_direct_gain: 255.5
    light_gain_mode: direct
    sipm_gain: 8.8e5
    light_gain_correction:
        4: 1.0859
        5: 1.0600
        6: 1.3500
        7: 1.0
charge: 
    clustering_pix_range: [1, 4]
    spread_thr_kev: 10.0
    noise_th_kev: 75.0
    core_exclude_pix:
        0: [0, 63]
        1: [0, 63]
        2: [0, 63]
        3: [0, 63]
    cross_fec_merge_drift_time_tolerance_us: 1.0
calibration: 
    energy: 
        gain_info_file: gainFuncParam3d.hdf5
        max_time_us: 66
        tp_channel: 17
        ccal: 8
    position:
        anode_pos_z_cm: 5.0

